<?php

namespace Atk\RegistrationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventDateRepository extends EntityRepository
{
}
